[package]
name = "portfolio"
version = "0.1.0"
edition = "2024"

[dependencies]
web-sys = { version = "0.3.85", features = ["Element"] }
yew = { version = "0.22.0", features = ["csr"] }
yew-router = "0.19.0"
